### ISSUE TITLE
成果物のデプロイ

### ISSUE THREAD

**Issue by seej000** [teamdev-Blue-May2023/work-space#33]

**Comment by Hiroshi0916** [comment]
1. HTMLファイルをリポジトリに追加します。 リポジトリが作成されたら、HTMLファイル（および必要なCSSやJavaScriptファイル）をリポジトリに追加します。
2. リポジトリの設定に移動します。 リポジトリのメインページに戻り、「Settings」タブをクリックします。
3. GitHub Pagesの設定を行います。 「Settings」ページでスクロールダウンして「GitHub Pages」セクションに移動します。ここで、「Source」ドロップダウンメニューで「main branch」を選択します。
4. 保存します。 「Save」または「Enforce HTTPS」をクリックして設定を保存します。
以上の手順を終えると、あなたのウェブサイトは https://<your-github-username>.github.io/<repository-name> というURLで公開されます。このURLはGitHub Pagesの設定セクションで確認することができます。
注意: GitHub Pagesでは静的なHTML、CSS、JavaScriptのみをホスティングできます。サーバーサイドの処理を必要とするウェブサイトはホスティングできません。
